server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://www.javarubberduck.com"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true